import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import {Sidebar, SideLink} from "./_components/Sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  return <>	
    <html lang="en">
      <body className={inter.className}>
        <Sidebar>
        <SideLink href="/">Home</SideLink>
        <SideLink href="/employees">Employee Card</SideLink>
        <SideLink href="/expenses">Expenses</SideLink>
        </Sidebar>
        {children}</body>
    </html>
    </>
}
